# Generated by Django 4.1 on 2023-09-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('sample_food', 'sample_food'), ('market_acquisition', 'market_acquisition'), ('sub_sample_food', 'sub_sample_food'), ('foundation_food', 'foundation_food'), ('agricultural_acquisition', 'agricultural_acquisition')], max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('food_category_id', models.IntegerField()),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
