# Generated by Django 4.1 on 2023-10-18 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('sample_food', 'sample_food'), ('market_acquisition', 'market_acquisition'), ('sub_sample_food', 'sub_sample_food'), ('foundation_food', 'foundation_food'), ('agricultural_acquisition', 'agricultural_acquisition')], max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('unit_name', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.nutrientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('data_points', models.IntegerField()),
                ('derivation_id', models.IntegerField()),
                ('min', models.FloatField(null=True)),
                ('max', models.FloatField(null=True)),
                ('median', models.FloatField(null=True)),
                ('footnote', models.CharField(max_length=15, null=True)),
                ('min_year_acquired', models.IntegerField(null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.foodcategory'),
        ),
    ]
