# Generated by Django 4.1 on 2023-09-11 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodstats_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('unit_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('data_points', models.IntegerField()),
                ('derivation_id', models.IntegerField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('median', models.FloatField()),
                ('footnote', models.CharField(max_length=15)),
                ('min_year_acquired', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.food')),
            ],
        ),
    ]
