# Generated by Django 4.2.4 on 2023-09-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodstats_api', '0002_nutrient_foodnutrient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='food_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.foodcategory'),
        ),
    ]
