# Generated by Django 4.1 on 2023-09-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodstats_api', '0004_rename_food_category_id_food_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrient',
            name='nutrient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodstats_api.nutrient'),
        ),
    ]
