# Generated by Django 4.1 on 2023-09-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstats_api', '0005_alter_foodnutrient_nutrient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrient',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='foodnutrient',
            old_name='nutrient_id',
            new_name='nutrient',
        ),
    ]
