# Generated by Django 4.1 on 2023-09-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstats_api', '0006_rename_food_id_foodnutrient_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutrient',
            name='footnote',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='median',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='min',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='foodnutrient',
            name='min_year_acquired',
            field=models.IntegerField(null=True),
        ),
    ]
